### ISSUE TITLE
Backup older than 1 month/5 last views should be deleted

### ISSUE THREAD

**Issue by inbalziv** [yaronthurm/Backy#18]
**Summary**
Backup view and files/folders older than 1 month or more than 5 last views should be deleted. It's a common behavior (windows delete also after one month) and that's way the user could have a normal backup folder size 

**Implementation** 
When a new backup starts to run it should check if (there are more than 5 views) and (there are views older than one month) --> delete them

**Comment by yaronthurm** [comment]
I don't think the app should automatically decides what's best for the user.
What if the user is happy about the fact that all the history is saved forever and he is willing to "pay" the extra storage costs?

I think that this kind of feature should at-least be configurable in the following aspects:
1. Whether it's On or Off
2. How many views to keep vs. How long to keep history vs. How much overhead storage is acceptable.
