### ISSUE TITLE
Getting exception in a few scenarios when the backup folder was deleted  

### ISSUE THREAD

**Issue by inbalziv** [yaronthurm/Backy#32]
**Description**
Deleting backup folder retrieves an exception in a few cases:
1. Click on View button right after loading the app
2. Click on Run 

![image](https://cloud.githubusercontent.com/assets/17785151/14389247/78ed6fd0-fdba-11e5-991c-8c25e6e6665e.png)

**Comment by yaronthurm** [comment]
The issue does not reproduce on my machine.
I will need more details. Stack Trace would be helpful (it's should be under the "Details" button from the error message).
