### ISSUE TITLE
View should be read only

### ISSUE THREAD

**Issue by inbalz** [yaronthurm/Backy#4]

**Comment by yaronthurm** [comment]
This is a bit tricky.
The View only shows the 'Projection' of the backed up files and enables you to open the underlying files that have been copied, but once opened, there is nothing preventing the user from editing the file (via Notepad for text files) or deleting it (via Photos app and clicking the 'Delete' button).

I tried marking the files 'read-only' but that only prevents editing, while not preventing deleting or renaming.

I am thinking about playing around with File Permissions or maybe just copying the file to a temp folder before opening it.

**Comment by yaronthurm** [comment]
Closed.
The app uses Windows File Permissions to remove all write permissions to the directories it created.
The only permission left is read for 'Everyone' so the files cannot be modified/deleted/renamed.
- Note - This method only protects the user from accidental modifications of the backed up files (as noted in the initial description of the issue).
  The user can always manually change back the permissions of the backed up files/directories and give himself write permissions. From that point, the user can mess up with the files and effectively prevents Backy from running correctly.
