### ISSUE TITLE
Support scheduling backup by time of day

### ISSUE THREAD

**Issue by yaronthurm** [yaronthurm/Backy#6]
Currently the only scheduling option is by elapsed time (backup every 'x' seconds).
Would like to see an option to schedule backup by the time of day, e.g. run backup every day at 2 AM, or run backup every Sunday, Tuesday and Thursday at 12:30 PM.

**Comment by inbalziv** [comment]
Scheduling backup every x secs doesnt make sense
Button should be on hidden as long as it not support scheduling by time of day

**Comment by yaronthurm** [comment]
Task Scheduler should be enough (especially since the app can run in no-UI mode).
